name: Build project

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: beet build
      - uses: mcbeet/check-commands@v1
        with:
          source: build/*
      - name: Get version
        id: get-version
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: beet.yml
          version: version
      - name: Copy built files
        run: 'mv ./build/**/* ./build && rmdir ./build/*_data_pack'
      - uses: actions/upload-artifact@v3
        with:
          name: ${{github.event.repository.name}}-${{steps.get-version.outputs.version}}
          path: build