name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Archive Release
      - uses: actions/checkout@master
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'woodcutter.zip'
          exclusions: '*.git* *.js'
        uses: actions/upload-artifact@v3
        with:
          name: woodcutter.zip
          path: woodcutter.zip