name: Release

env:
  modrinth_project_id: "boWXaKrz"
  minecraft_versions: 1.19,1.19.1,1.19.2,1.19.3

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get-version
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: beet.yml
          version: version
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          skip_unpack: true
          path: out
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*.zip
      - name: Create Modrinth Release
        if: ${{ env.modrinth_project_id != null }}
        uses: RubixDev/modrinth-upload@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file_path: out/${{github.event.repository.name}}-${{steps.get-version.outputs.version}}.zip
          name: ${{ github.event.repository.name }} ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          game_versions: ${{env.minecraft_versions}}
          loaders: datapack 
          featured: true
          project_id: ${{env.modrinth_project_id}}